# Generated by Django 4.1 on 2022-09-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listingitem'),
        ),
    ]
