# Generated by Django 4.1 on 2022-09-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_listing_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listingitem'),
        ),
    ]
