# Generated by Django 4.1 on 2022-09-07 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listingitem_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
